"""KPI catalogue renderer (SPEC 7.3): ``docs/KPI_CATALOGUE.md`` generated from code.

THE MODEL ADVISES, DETERMINISTIC CODE DECIDES, A NAMED HUMAN OWNS EVERY THRESHOLD.

The markdown is generated from ``KPI_REGISTRY`` and ``KPI_TREE`` and is never
hand-edited. Per KPI it lists id, name, definition, formula, source tables,
the "measurable from" sentence, unit, direction and min_n; when a
``KpiTargets`` object is passed, the target and its owner are shown as well.
"""

from __future__ import annotations

from pathlib import Path

from restwert.config import KpiTargets, load_kpi_targets
from restwert.kpi.registry import KPI_REGISTRY, KPI_TREE, KpiSpec
from restwert.paths import CONFIG_DIR, DOCS_DIR

GOVERNANCE_SENTENCE = "THE MODEL ADVISES, DETERMINISTIC CODE DECIDES, A NAMED HUMAN OWNS EVERY THRESHOLD."

_DIRECTION_TEXT = {
    "up": "higher is better",
    "down": "lower is better",
    "zero": "closer to zero is better",
    "one": "closer to one is better",
}


def _kpi_section(spec: KpiSpec, targets: KpiTargets | None) -> str:
    lines = [
        f"### {spec.name}",
        "",
        f"- **id:** `{spec.kpi_id}`",
        f"- **definition:** {spec.definition}",
        f"- **formula:** `{spec.formula_text}`",
        f"- **source tables:** {', '.join(f'`{t}`' for t in spec.source_tables)}",
        f"- **measurable from:** {spec.measurable_from}",
        f"- **unit:** {spec.unit}",
        f"- **direction:** {spec.direction} ({_DIRECTION_TEXT.get(spec.direction, spec.direction)})",
        f"- **min_n:** {spec.min_n} (below this the value is stored but flagged not_measurable)",
    ]
    if targets is not None:
        target = targets.targets.get(spec.kpi_id)
        if target is not None:
            lines.append(f"- **target:** {target} (owner: {targets.targets_owner}, placeholder)")
    lines.append("")
    return "\n".join(lines)


def render_catalogue(registry: dict[str, KpiSpec] = KPI_REGISTRY, tree: list = KPI_TREE, targets: KpiTargets | None = None) -> str:
    """Render the full catalogue as markdown text."""

    out: list[str] = [
        "# KPI catalogue",
        "",
        "GENERATED by `restwert.kpi.catalogue.write_catalogue` from `restwert/kpi/*.py`. Do not edit by hand; "
        "change the KPI definition in code and regenerate with `python -m restwert kpis --catalogue`.",
        "",
        f"> {GOVERNANCE_SENTENCE}",
        "",
        "Every KPI reads DuckDB tables only. A KPI whose denominator is 0, whose required column is missing or "
        "entirely NULL, or whose observation count is below its `min_n` is reported as `not_measurable` with "
        "`value = None` and a note that says why, never as 0. On synthetic data every number describes the "
        "synthetic design parameters in `config/generator.yaml`, not a market.",
        "",
    ]
    if targets is not None:
        plan = ", ".join(f"{year}: {value:,.0f} EUR" for year, value in sorted(targets.savings_plan_eur.items()))
        out += [
            f"Savings plan (owner: {targets.savings_plan_owner}, placeholder values): {plan}.",
            f"KPI targets owner: {targets.targets_owner}.",
            "",
        ]
    out += ["## KPI tree", ""]
    for area, ids in tree:
        names = ", ".join(registry[k].name for k in ids if k in registry)
        out.append(f"- **{area}**: {names}")
    out.append("")
    listed: set[str] = set()
    for area, ids in tree:
        out += [f"## {area}", ""]
        for kpi_id in ids:
            spec = registry.get(kpi_id)
            if spec is None:
                continue
            listed.add(kpi_id)
            out.append(_kpi_section(spec, targets))
    leftovers = [k for k in registry if k not in listed]
    if leftovers:
        out += ["## Unassigned", ""]
        for kpi_id in leftovers:
            out.append(_kpi_section(registry[kpi_id], targets))
    return "\n".join(out).rstrip() + "\n"


def write_catalogue(path: Path = DOCS_DIR / "KPI_CATALOGUE.md", targets: KpiTargets | None = None) -> Path:
    """Write the catalogue to ``path`` (UTF-8, no BOM); loads targets from config when not given."""

    if targets is None:
        targets_path = CONFIG_DIR / "kpi_targets.yaml"
        if targets_path.exists():
            try:
                targets = load_kpi_targets(targets_path)
            except Exception:  # noqa: BLE001  (a broken targets file must not block the catalogue)
                targets = None
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_catalogue(targets=targets), encoding="utf-8", newline="\n")
    return path


__all__ = ["GOVERNANCE_SENTENCE", "render_catalogue", "write_catalogue"]
