"""Gold KPI catalogue renderer: ``docs/GOLD_KPIS.md`` generated from code (SPEC_v0.2 section 8.3).

THE MODEL ADVISES, DETERMINISTIC CODE DECIDES, A NAMED HUMAN OWNS EVERY THRESHOLD.

The markdown is generated from ``GOLD_KPI_REGISTRY`` and never hand-edited.
Per KPI it lists id, page, owner, definition, formula, source tables, unit,
direction and min_n; when a ``KpiTargets`` object is passed and carries a
matching key, the target and its owner are shown too.
"""

from __future__ import annotations

from pathlib import Path

from restwert.config import KpiTargets, load_kpi_targets
from restwert.gold.registry import GOLD_KPI_REGISTRY, GOLD_KPI_TREE, PAGE_OWNERS, GoldKpiSpec
from restwert.kpi.catalogue import GOVERNANCE_SENTENCE
from restwert.paths import CONFIG_DIR, DOCS_DIR

_DIRECTION_TEXT = {
    "up": "higher is better",
    "down": "lower is better",
    "zero": "closer to zero is better",
    "one": "closer to one is better",
}


def _ensure_registry_loaded() -> None:
    import restwert.gold.kpis  # noqa: F401


def _min_n_text(spec: GoldKpiSpec, targets: KpiTargets | None) -> str:
    from restwert.gold.run import effective_min_n, min_n_owner

    value = effective_min_n(spec, targets)
    if targets is not None and getattr(targets, "min_n", None) and spec.kpi_id in targets.min_n:
        return f"{value} (config/kpi_targets.yaml, owner {min_n_owner(targets)}; below this the value is stored but flagged not_measurable)"
    return f"{value} (registry default, no value in config/kpi_targets.yaml; below this the value is stored but flagged not_measurable)"


def _kpi_section(spec: GoldKpiSpec, targets: KpiTargets | None) -> str:
    lines = [
        f"### {spec.name}",
        "",
        f"- **id:** `{spec.kpi_id}`",
        f"- **page:** {spec.page}",
        f"- **owner:** {spec.owner}",
        f"- **definition:** {spec.definition}",
        f"- **formula:** `{spec.formula_text}`",
        f"- **source tables:** {', '.join(f'`{t}`' for t in spec.source_tables)}",
        f"- **unit:** {spec.unit}",
        f"- **direction:** {spec.direction} ({_DIRECTION_TEXT.get(spec.direction, spec.direction)})",
        f"- **min_n:** {_min_n_text(spec, targets)}",
    ]
    if targets is not None:
        target = targets.targets.get(spec.kpi_id)
        if target is not None:
            lines.append(f"- **target:** {target} (owner: {targets.targets_owner}, placeholder)")
    lines.append("")
    return "\n".join(lines)


def render_gold_catalogue(targets: KpiTargets | None = None) -> str:
    """Render the gold catalogue as markdown text, one section per cycle page."""

    _ensure_registry_loaded()
    out: list[str] = [
        "# Gold KPI catalogue (v0.2 cycle pages)",
        "",
        "GENERATED by `restwert.gold.catalogue.write_gold_catalogue` from `restwert/gold/kpis.py`. Do not edit by hand; "
        "change the KPI definition in code and regenerate with `python -m restwert kpis --catalogue`.",
        "",
        f"> {GOVERNANCE_SENTENCE}",
        "",
        "These KPIs read the silver ledger, the timeline, the reconciliation and the gold tables of the data lake and "
        "write `gold.kpi_values` and `gold.kpi_breakdown`. The v0.1 registry (20 KPIs, five areas, `docs/KPI_CATALOGUE.md`) "
        "is frozen and untouched. A KPI whose denominator is 0 or whose table or column is missing is reported as "
        "`not_measurable` with `value = None` and a note that says why, never as 0; a KPI whose observation count is below "
        "its `min_n` (`config/kpi_targets.yaml`, owned) keeps the value for reference but is flagged `not_measurable` and the "
        "dashboard tile reads n/a with the reason. "
        "On synthetic data every number describes the design parameters in `config/lake.yaml` and `data/lake/SYNTHETIC.md`, "
        "not a market.",
        "",
        "Every page has a named owner (placeholder names as in the config files):",
        "",
    ]
    for page, owner in PAGE_OWNERS.items():
        out.append(f"- **{page}**: {owner}")
    out += ["", "## KPI tree", ""]
    for page, ids in GOLD_KPI_TREE:
        names = ", ".join(GOLD_KPI_REGISTRY[k].name for k in ids if k in GOLD_KPI_REGISTRY)
        out.append(f"- **{page}**: {names if names else '(none)'}")
    out.append("")
    listed: set[str] = set()
    for page, ids in GOLD_KPI_TREE:
        out += [f"## {page}", ""]
        for kpi_id in ids:
            spec = GOLD_KPI_REGISTRY.get(kpi_id)
            if spec is None:
                continue
            listed.add(kpi_id)
            out.append(_kpi_section(spec, targets))
    leftovers = [k for k in GOLD_KPI_REGISTRY if k not in listed]
    if leftovers:
        out += ["## Unassigned", ""]
        for kpi_id in leftovers:
            out.append(_kpi_section(GOLD_KPI_REGISTRY[kpi_id], targets))
    return "\n".join(out).rstrip() + "\n"


def write_gold_catalogue(path: Path = DOCS_DIR / "GOLD_KPIS.md", targets: KpiTargets | None = None) -> Path:
    """Write the gold catalogue to ``path`` (UTF-8, no BOM, LF); loads targets from config when not given."""

    if targets is None:
        targets_path = CONFIG_DIR / "kpi_targets.yaml"
        if targets_path.exists():
            try:
                targets = load_kpi_targets(targets_path)
            except Exception:  # noqa: BLE001  (a broken targets file must not block the catalogue)
                targets = None
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_gold_catalogue(targets=targets), encoding="utf-8", newline="\n")
    return path


__all__ = ["render_gold_catalogue", "write_gold_catalogue"]
