"""Synthetic data generator (SPEC.md section 3: module 1, generator + load).

THE MODEL ADVISES, DETERMINISTIC CODE DECIDES, A NAMED HUMAN OWNS EVERY THRESHOLD.

Everything produced here is synthetic and says so: every row carries
``is_synthetic = True``, every CSV starts with a ``# SYNTHETIC DATA`` line, and
``data/SYNTHETIC.md`` documents seed and counts. No customer, supplier or
employer is real; suppliers are ``Supplier-A`` .. ``Supplier-L``, customers
``CUST-0001`` .., models ``P-Gen05`` style. No market benchmark is quoted.

Generation is deterministic for a given seed: ONE ``numpy.random.default_rng(seed)``
is passed through the builders in a fixed call order (catalogue, fleet, rentals,
events, refurbishment, resale, supplier contracts, indirect spend).
"""

from __future__ import annotations

import time
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

import numpy as np
import pandas as pd

from restwert import __version__
from restwert.config import GeneratorConfig
from restwert.generate.catalogue import build_catalogue
from restwert.generate.events import build_events
from restwert.generate.fleet import DEVICE_COLUMNS, build_devices
from restwert.generate.procurement import build_indirect_spend, build_supplier_contracts, link_purchase_orders
from restwert.generate.recommerce import build_refurbishment, build_resale
from restwert.generate.rentals import build_rental_contracts
from restwert.paths import RAW_CSV_DIR
from restwert.records import RunSummary
from restwert.schema import SOURCE_TABLES, validate_frame

SYNTHETIC_SENTENCE = (
    "Every number in this dataset is a synthetic design parameter from config/generator.yaml. "
    "No market benchmark, no customer, no supplier and no employer is real."
)


def generate_all(
    cfg: GeneratorConfig, seed: int | None = None, n_devices: int | None = None
) -> dict[str, pd.DataFrame]:
    """Generate every SOURCE table, keyed by table name in ``schema.SOURCE_TABLES`` order.

    Every frame carries ``is_synthetic = True`` and ``source_file = "<table>.csv"`` and
    has been passed through ``schema.validate_frame`` (DDL column order, python dates).
    """
    seed = cfg.seed if seed is None else int(seed)
    n = cfg.n_devices if n_devices is None else int(n_devices)
    if n < 1:
        raise ValueError("n_devices must be >= 1")
    cfg = cfg.model_copy(update={"seed": seed, "n_devices": n}, deep=True)
    rng = np.random.default_rng(seed)

    catalogue = build_catalogue(cfg, rng)
    devices, purchase_orders, benchmarks = build_devices(cfg, catalogue, rng)
    contracts = build_rental_contracts(cfg, devices, rng)
    first_contract = (
        contracts.sort_values(["start_date", "contract_id"], kind="stable")
        .drop_duplicates("serial", keep="first")
        .set_index("serial")["contract_id"]
    )
    devices["contract_id"] = devices["serial"].map(first_contract)
    devices["contract_id"] = [None if pd.isna(v) else str(v) for v in devices["contract_id"]]
    events, contracts, devices = build_events(cfg, devices, contracts, rng)
    refurb = build_refurbishment(cfg, events, devices, rng)
    resale = build_resale(cfg, devices, refurb, events, catalogue, rng)
    supplier_contracts = build_supplier_contracts(cfg, rng, purchase_orders=purchase_orders)
    purchase_orders = link_purchase_orders(purchase_orders, supplier_contracts)
    indirect = build_indirect_spend(cfg, supplier_contracts, rng)

    devices = devices[DEVICE_COLUMNS]
    raw = {
        "model_catalogue": catalogue,
        "devices": devices,
        "rental_contracts": contracts,
        "events": events,
        "refurbishment": refurb,
        "resale": resale,
        "supplier_contracts": supplier_contracts,
        "purchase_orders": purchase_orders,
        "indirect_spend": indirect,
        "benchmarks": benchmarks,
    }
    frames: dict[str, pd.DataFrame] = {}
    for table in SOURCE_TABLES:
        df = raw[table].copy()
        df["is_synthetic"] = True
        df["source_file"] = f"{table}.csv"
        frames[table] = validate_frame(table, df)
    return frames


def write_csvs(frames: dict[str, pd.DataFrame], out_dir: Path = RAW_CSV_DIR, seed: int = 42) -> list[Path]:
    """Write ``<table>.csv`` per frame: comment line, header, rows; UTF-8 without BOM, ISO dates."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    generated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    written: list[Path] = []
    for table, df in frames.items():
        path = out_dir / f"{table}.csv"
        with open(path, "w", encoding="utf-8", newline="") as fh:
            fh.write(f"# SYNTHETIC DATA - generated by restwert generate, seed={seed}, generated_at={generated_at}\n")
            df.to_csv(fh, index=False, lineterminator="\n", date_format="%Y-%m-%d")
        written.append(path)
    return written


def render_synthetic_md(cfg: GeneratorConfig, seed: int, counts: dict[str, int], generated_at: str | None = None) -> str:
    generated_at = generated_at or datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    lines = [
        "# SYNTHETIC DATA",
        "",
        f"Generated by `restwert generate` (package version {__version__}) at {generated_at}.",
        "",
        f"- seed: `{seed}`",
        f"- n_devices: `{cfg.n_devices}` (plus 5 % spares per family)",
        f"- history: `{cfg.history_start.isoformat()}` to `{cfg.purchase_end.isoformat()}`, as_of `{cfg.as_of.isoformat()}`",
        f"- families: {', '.join(f'`{f}`' for f in cfg.families)}",
        "",
        "## Row counts",
        "",
        "| Table | Rows |",
        "|---|---:|",
    ]
    for table in SOURCE_TABLES:
        lines.append(f"| `{table}` | {counts.get(table, 0)} |")
    lines += [
        "",
        SYNTHETIC_SENTENCE,
        "",
        "Every row carries `is_synthetic = true`. Each CSV in `data/raw_csv/` starts with a "
        "`# SYNTHETIC DATA` comment line. Delete this folder and load your own CSVs (with "
        "`is_synthetic = false`) to work on real data; see README section 9.",
        "",
        f"Generator version: {__version__}",
        "",
    ]
    return "\n".join(lines)


def write_synthetic_md(out_dir: Path, cfg: GeneratorConfig, seed: int, counts: dict[str, int]) -> Path:
    """Write ``<out_dir>/SYNTHETIC.md`` (``data/SYNTHETIC.md`` in the standard layout)."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "SYNTHETIC.md"
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render_synthetic_md(cfg, seed, counts))
    return path


def run_generate(cfg: GeneratorConfig, seed: int, n_devices: int, out_dir: Path) -> RunSummary:
    """Generate, write CSVs to ``out_dir`` and ``SYNTHETIC.md`` next to it (its parent folder)."""
    started = datetime.now(timezone.utc)
    t0 = time.perf_counter()
    out_dir = Path(out_dir)
    frames = generate_all(cfg, seed=seed, n_devices=n_devices)
    write_csvs(frames, out_dir, seed=seed)
    counts = {t: int(len(df)) for t, df in frames.items()}
    md_dir = out_dir.parent if out_dir.name == "raw_csv" else out_dir
    md_path = write_synthetic_md(md_dir, cfg.model_copy(update={"seed": seed, "n_devices": n_devices}), seed, counts)
    finished = datetime.now(timezone.utc)
    return RunSummary(
        command="generate",
        run_id=f"generate-{started:%Y%m%d%H%M%S}-{uuid4().hex[:4]}",
        started_at=started,
        finished_at=finished,
        seconds=round(time.perf_counter() - t0, 3),
        counts=counts,
        notes=[f"csv_dir={out_dir}", f"synthetic_md={md_path}", f"seed={seed}", f"n_devices={n_devices}"],
    )


__all__ = [
    "generate_all",
    "write_csvs",
    "write_synthetic_md",
    "render_synthetic_md",
    "run_generate",
    "SYNTHETIC_SENTENCE",
]
